### ISSUE TITLE
Преработки

### ISSUE THREAD

**Issue by ghost** [chitanka/chitanka-installer#1]
Трябва да се преработи:
- [x] Промяна на имената на променливите - да се използват само малки букви
- [ ] Добавяне на прединсталационни проверки
- [x] Извеждане на излишните части извън chitanka.sh
- [ ] Екрани - например, при въвеждането на домейн, екранът се различава от първоначалния.
- [ ] Някои текстове са твърде императивни.
- [ ] Малко по-подробен help
- [ ] .md файл за github

**Comment by ghost** [comment]
Имената на функциите са поправени.
Допълнителните неща са преместени в includes/ и extra/

**Comment by krasimirstoev** [comment]
@bmanolov, това също е за затваряне.
