### ISSUE TITLE
NGINX 502 Bad Gateway (+ решение)

### ISSUE THREAD

**Issue by semerdzhiev** [chitanka/chitanka-installer#6]
След като инсталатора приключи, при опит да се достъпи локалната инсталация, се получава следната грешка:

```
NGINX 502 Bad Gateway
```

Причината е в конфигурацията на nginx за читанка (`nginx-vhost.conf`). Там е указано следното за fastcgi_pass:

```
fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
```

Ако обаче има инсталирана по-нова версия, трябва пътят да се актуализира. Например:

```
fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
```

Ако инсталацията вече е направена, ето стъпките:

1. Отваря се `/etc/nginx/sites-enabled/chitanka`
2. Редактира се съответния ред, като се отрази текущата версия.
3. Рестартира се nginx.

**Comment by krasimirstoev** [comment]
Направо е хардкоднато да търси 7.3, макар да е добра идея да видим какви са вариантите първо да се проверява дали (и къде) живее .sock файлът.
